apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pulse.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pulse.labels" . | nindent 4 }}
data:
  PULSE_POSTGRES_URL: {{ .Values.postgres.url | quote }}
  PULSE_REDIS_ADDR: {{ .Values.redis.addr | quote }}
  PULSE_ETCD_ENDPOINTS: {{ .Values.etcd.endpoints | quote }}
  PULSE_PORT: {{ .Values.api.port | quote }}
