apiVersion: v1
kind: ConfigMap
metadata:
  name: Sluice-config
  namespace: Sluice
data:
  Sluice_POSTGRES_URL: "postgres://Sluice:Sluice@postgres:5432/Sluice?sslmode=disable"
  Sluice_REDIS_ADDR: "redis:6379"
  Sluice_ETCD_ENDPOINTS: "etcd:2379"
  Sluice_PORT: "8080"
